### PR TITLE
Added new route to wake up heroku via newrelic

### PR DESCRIPTION
**Pull request by Bronskiy**
Prevent heroku from sleeping by monitoring https://[heroku_app_name].herokuapp.com/wake-up link via newrelic.
[stackoverflow](https://stackoverflow.com/a/5482285/2549284)

### CODE REVIEW

**Comment by stevenleeg** [comment]
Hey thanks for the PR!

I'm a little hesitant to add in a dummy route when it seems like it'd work just as well to allow NewRelic to ping any other route on the server to wake up Heroku. Is there a reason for needing an explicit dummy route?

**Comment by Bronskiy** [comment]
Hi!
A dummy route will allow us to avoid Failures in the report. So we can get failure message notification when the heroku app will be really unavailable.
I tried to use ttps://[heroku_app_name].herokuapp.com/alexa link and it works fine to wake up server but it is generated Failures on newrelic. so dummy route seems harmless and useful.

**Comment by stevenleeg** [comment]
Oh I see, that does seem useful then. Merging, and thanks for the contribution!

**Comment by famewolf** [comment]
@Bronskiy  How are you setting up the activity monitor?  I believe I connected the service to heroku and have the free hours but I'm not seeing where to go to setup the monitor.

**Comment by Bronskiy** [comment]
Synthetics -> Add new -> Monitor URL|All locations|30 min

**Pull request merged**
