### PR TITLE
Library Intent

### PR DESCRIPTION
**Pull request by PostsDesert**
Added a library intent and `api.increment_song_playcount()`.

### CODE REVIEW

**Comment by stevenleeg** [comment]
This looks great. My only thought is that maybe we should make this shuffle instead of playing the library in order each time? Otherwise you'll be starting at the same song of a 50,000 song library each time when you might just want something random.

**Comment by PostsDesert** [comment]
Yep, added that.

**Comment by stevenleeg** [comment]
Looks great, thanks for the addition!

**Comment by digiltd** [comment]
Hi, I can't seem to get any library track to play with or without a subscription.

When I use the "play music from my library" i get an error about being the list index being out of range.

```bash
list index out of range23:40:34 web.1  |   File "/Users/sam/Development/geemusic/.venv/lib/python2.7/site-packages/flask_ask/core.py", line 559, in _flask_view_func
23:40:34 web.1  |     result = self._map_intent_to_view_func(self.request.intent)()
23:40:34 web.1  |   File "/Users/sam/Development/geemusic/geemusic/intents/selection.py", line 174, in play_library
23:40:34 web.1  |     first_song_id = queue.shuffle_mode(True)
23:40:34 web.1  |   File "/Users/sam/Development/geemusic/geemusic/utils/music_queue.py", line 77, in shuffle_mode
23:40:34 web.1  |     return self.song_ids[self.current_index]
23:40:34 web.1  | IndexError: list index out of range
```

**Comment by PostsDesert** [comment]
Can you try [this branch](https://github.com/PostsDesert/geemusic). It's working for me.

**Pull request merged**
