### PR TITLE
Added new interactionModel json format combining intentSchema and sam…

### PR DESCRIPTION
**Pull request by aplocher**
…pleUtterances.  This is the new json format that seems to be required by Amazon.  Note: I tried to not touch the non_us stuff, as I'm unfamiliar with it.

### CODE REVIEW

**Comment by aplocher** [comment]
#198

**Comment by fergyfresh** [comment]
I'll test this out tonight, unless someone else wants to beat me to it.

**Comment by stevenleeg** [comment]
Sweet, just let me know and I'll merge this in once you give it the 👍 .

Some kind of CI would be incredible. A quick search yielded [this](https://bespoken.io/blog/alexa-skill-automation-testing-integration-delivery/) article discussing how they've managed to unit test/ci their skill to make sure everything is still working. Perhaps it's something worth looking into, however I don't have a ton of time to put into it as of right now (hence my mostly managerial role in the project as of late). That said, if anyone has some time/interest in setting such a thing up I'd be happy to do what I can to help make it happen.

**Comment by fergyfresh** [comment]
In that article they still use the decoupled `intentSchema` and `sampleUtterances` and I guess its supposed to be coupled now. So approving this PR, which seems like the right thing to do, would not allow us to use the solution you linked. Its also JS and not Python.

**Comment by aplocher** [comment]
Sorry been busy on a project the last week (pretty much shut myself off from the world after submitting this lol).  

To answer your question about if it's been tested: I've been using this the last week or so to the extent that I use GeeMusic, so no meaningful unit tests, but "Tell GeeMusic to start playlist xxx" or the other few commands I use have been working :)

**Comment by fergyfresh** [comment]
Where do you paste that stuff into? The Code Editor? My stuff still uses the old interaction model with the `intentsSchema` section and the `sampleAssets` section. Do you have to update to the `Builder` and then use the `Code Editor`?

**Comment by stevenleeg** [comment]
Is this good to merge? I'm still on the road and haven't had a chance to test it.

**Pull request merged**
