### PR TITLE
Use hashlib instead of md5, and fix README

### PR DESCRIPTION
**Pull request by tiratatp**

### CODE REVIEW

**Comment by stevenleeg** [comment]
Any particular reason for the switch from md5 to hashlib?

**Comment by audioeng** [comment]
Guessing because it has been deprecated since python 2.5?

https://docs.python.org/2/library/md5.html

**Comment by tiratatp** [comment]
It was causing error when deploying on heroku.

**Comment by stevenleeg** [comment]
awesome, thanks for the patch! merging now.

**Pull request merged**
