### PR TITLE
Install git in docker container to use pip packages from git+ssh

### PR DESCRIPTION
**Pull request by kressh**
Hello!

Thanks for awesome project! Had troubles building docker image because of package from git: https://github.com/stevenleeg/geemusic/blob/master/requirements.txt#L20

So I added git package to alpine.
Also I added `.git` directory to `.dockerignore` and additional building step where build deps removed from container system.

### CODE REVIEW

**Comment by stevenleeg** [comment]
Hmm, I don't really get what this is doing. It looks like you just moved the build depends to an environment variable and removed them after installing the dependencies?

**Comment by kressh** [comment]
The most important part is installing git, which fixes broken docker build because of: https://github.com/stevenleeg/geemusic/blob/master/requirements.txt#L20

Second - removing gcc, make, musl after we compiled all our libraries seems like a good practice.

Third - ignore .git files to speed up container building.

**Comment by fergyfresh** [comment]
@kressh sorry about breaking the Docker build. I needed to use that fork originally because `flask-ask` broke the WSGI portion for Python3.6 because they switched `StringIO` to `BytesIO`, but AWS Lambda functions don't support byte-like request bodies unless you use ApiGateway. I use ApiGateway now so this dependency isn't exactly necessary. I will clean up the `requirements.txt` file when I get home today, until then just keep using your working version if you don't mind.

@stevenleeg this is why I want tests!

**Comment by stevenleeg** [comment]
@fergyfresh yes yes yes pls tests always tests ❤️

**Comment by fergyfresh** [comment]
@kressh wanna try it out? I fixed the dependency issue.

**Comment by fergyfresh** [comment]
Fixed in #231.

**Pull request closed without merging**
