### PR TITLE
Mehdy driouech fr complete trad

### PR DESCRIPTION
**Pull request by MehdyDriouech**

### CODE REVIEW

**Comment by fergyfresh** [comment]
Also, I made a fix two days ago that fixes an issue where the text for the `PlaySimilarSongRadio` text wasn't quite right. https://github.com/stevenleeg/geemusic/blob/master/geemusic/templates/en.yaml#L29 if you don't add that in your `fr.yaml` that specific intent won't work for the French version.

**Comment by MehdyDriouech** [comment]
added ;)

Le mer. 13 juin 2018 à 14:52, Billy Ferguson <notifications@github.com> a
écrit :

**Comment by fergyfresh** [comment]
Almost there! The only problems I have now are that you have two Pull Request's open with almost the same changes and the other problem is that you can't change the words on the left side of the `:` in the yaml file. For example, lines 39 and 40 need to say what they say in the original `en.yaml` file.

The last thing is that on line 51 you have one too many sets of double quotes which is bad YAML.

**Comment by MehdyDriouech** [comment]
i'll close the PR and i'll make a good one ;)

**Pull request closed without merging**
