### PR TITLE
Upgrade packages to support Python 3.7

### PR DESCRIPTION
**Pull request by mikeage**
* Cryptography: https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#23---2018-07-18 (python 3.7 added in 2.3)
* PyYAML: https://pyyaml.org/wiki/PyYAML (python 3.7 added in 3.13)

### CODE REVIEW

**Comment by mikeage** [comment]
Resolves #257 (hopefully)

**Comment by fergyfresh** [comment]
I'll try this at home later.

**Comment by fergyfresh** [comment]
Why should we move to 3.6? Isn't 3.7 still not stable yet?

**Comment by mikeage** [comment]
Sorry, not sure I follow the question. This PR should support both 3.6 and 3.7.

Note that a bunch of other packages also have upgrades; possibly the most important is gmusicapi itself (which, in the latest version, supports ios:XXXXX IDs as well as Android device iDs), but also Flask has some significant improvements. Maybe for later...

**Comment by fergyfresh** [comment]
Oh ok. I thought you were suggesting I move the travis CI to only check 3.6.

**Comment by mikeage** [comment]
No. I would not recommend that, either, since the Dockerfile still uses python 3.6 (for now)

**Comment by fergyfresh** [comment]
Sorry I was reading this on the train and didn't have enough service to check the commits/file changes. This is great!

**Pull request merged**
