### PR TITLE
Adds basic integration tests and travis-ci.

### PR DESCRIPTION
**Pull request by fergyfresh**
So I hacked through this the other night, there's still some stuff I have to work though and clean up to make sure that the integration tests actually test the correct things. There's a lot of mocking we would have to do based on our assumptions of some things, gmusicapi and Heroku/AWS etc. 

Haven't done these kind of "smoke tests" before so any help or advice would be greatly accepted!

I also had to add the environment variables inside of travis instead of putting them in the YAML file because security, but its only a 1time thing and they are the same exact variables as you have to setup for deployment (Heroku, ngrok, Lambda, etc). There is a way to encrypt them, but I don't really wanna have my credentials living out there in the wild even if they are encrypted.

### CODE REVIEW

**Comment by fergyfresh** [comment]
The first two tests are for testing that the app builds and basic Flask-Ask functionality extensions work properly and the third one is an integration test that tests that the stream url gets generated properly without erroring out. We can trust the `gmusicapi` CI for most of our stuff, just trying to get CI propped up around features I care about ;)

**Comment by fergyfresh** [comment]
@stevenleeg hey man. I finally got around to figuring out how to end-to-end functionally test a few pieces of functionality. Over time we can test everything, but 8 tests are better than 0 tests. Setting it up with travis-ci is wicked easy. If you need help I'll be available all afternoon/most of tonight/and all morning tomorrow.

**Comment by stevenleeg** [comment]
Sorry about the delay here. This looks awesome! Let me see what I can do to get Travis CI on this repo.

**Comment by stevenleeg** [comment]
Hmm @fergyfresh are you using your google username/password in ENV variables while testing?

**Comment by fergyfresh** [comment]
This is wicked wonky, since you accepted the pull request the setup and tests that were run on the `adds-test` branch of my fork are gone. Unless there is some weird under-belly of this UI that I haven't found yet.

To be safe, you could just use the same ones as the deployed version of your app:
```
GOOGLE_EMAIL="example@gmail.com"
GOOGLE_PASSWORD="app_password"
APP_URL="I_used_my_API_Gateway_Deplyed_version_but_you_could_probably_use_localhost"
```

**Comment by fergyfresh** [comment]
I don't remember if I used the ANDROID_ID or not and there's no way to check now, but I promise I had passing tests!

**Comment by fergyfresh** [comment]
So I used these:

APP_URL="my_deployed_copy"
ASK_VERIFY_REQUESTS="False"
DEBUG_MODE="True"
GOOGLE_EMAIL="myactualemail@gmail.com"
GOOGLE_PASSWORD="app_password"

I did not use `ANDROID_ID`. Confirmed!

**Comment by fergyfresh** [comment]
@stevenleeg let me know if you need anything else. I think you should be good now though, I meant to dump those out before, oops!

**Comment by mikeage** [comment]
looks like you need to have these environment vars set in .travis.yml (and set to a real email/password), or else all the tests are failing

**Comment by fergyfresh** [comment]
https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

I have the `ANDROID_ID` env var set now and it will work. Maybe we have a staging branch to get around the tests not being able to be run on PR. They seemingly can only be run on commit per that link there. In less someone can come up with a workaround.

**Comment by mikeage** [comment]
Why do the tests need an ANDROID_ID anyway? Would it be possible (better?) just to mock the get_stream_url call from gmusicapi? 

If you need the ANDROID_ID, I don't see an alternative to a staging branch (or something like git flow). You could try registering a fake email and using that for all tests, but I assume when Google sees so many logins from so many different IPs, they'll give you problems.

**Comment by fergyfresh** [comment]
You only around the IP problem with an android I'd. We could mock that call
too though.

**Pull request merged**
