### PR TITLE
Play/pause potential fix

### PR DESCRIPTION
**Pull request by Danondso**
I'm grabbing the offsetInMilliseconds from the ask.context and passing that into play() along with the stream_url.

### CODE REVIEW

**Comment by stevenleeg** [comment]
This looks simple, I like it.

I'll be out for today but will test this as soon as I get home and hopefully merge it. Thanks for the contribution!

**Comment by stevenleeg** [comment]
Currently messing around with this and have found a couple of bugs, the biggest of which is due to individual tracks not being added to the queue (so alexa reports that nothing is playing when you attempt to resume). I think I have a solution so hang tight and I'll submit a patch for you to take a look at.

**Comment by Danondso** [comment]
Sounds good, I'll check it out after work tomorrow
.

**Comment by stevenleeg** [comment]
I brought your PR into the `pause-support` branch [here](https://github.com/stevenleeg/geemusic/compare/pause-support) and made a few changes that should put this on a good track.

I'm unfortunately still unable to get this to work reliably, as saying `alexa, play` results in these requests:

screen shot 2017-01-04 at 00 14 47

but no music actually getting played. What's strange is that there are six requests being made (it seems like everything is being duplicated?), the stream URLs are being requested properly, yet there is still no music. Weirdly enough, when it does decide to start playing music the song _is_ resumed from its last played position, so at least that part works.

Any chance you could checkout this branch and see if you can reproduce the same sort of behavior? In case you haven't tried this yet, the http request interception is being done by [ngrok](https://ngrok.com/), which is a huge help for these sorts of issues.

**Comment by Danondso** [comment]
@Tyzer34 just read the response on your post. It's sounding like it's something that needs to be handled by flask-ask. Initially when I started trying to fix this I was messing around with the framework to see if I could pass it in that way. I might check into that again now. 

@stevenleeg When I was trying to get that to work on my repo I was having several bad requests along with the good one in ngrok. I'm about to start taking a look at this branch here and I'll let you know if it's the same for me.

**Comment by Danondso** [comment]
So I set this up separately with foreman and pycharm on ubuntu and every time I try to play a song I get a 404 on the stream along with a 400. Have you run into that issue before?

POST /alexa                                    400 BAD REQUEST                  
GET  /alexa/stream/To7r2zqnkq3ggbwo7vrk2haoami 404 NOT FOUND                    
POST /alexa                                    200 OK                           
POST /alexa                                    400 BAD REQUEST                  
GET  /alexa/stream/Tgp2bnzf4muiyfn73ef3cbsvc4y 404 NOT FOUND                    
POST /alexa                                    200 OK

**Comment by Danondso** [comment]
So apparently this comes back to an issue within flask-ask. I brought the up the issue <a href="https://github.com/johnwheeler/flask-ask/issues/71" target="_blank"> here </a> when I was doing research and apparently someone has identified and fixed the problem. 

To quote treethought: 
>Hey Danondso, I've been working on this issue and have fixed it so that the stream resumes from >where it was paused. I'll try to clean up my work and push the change. I'm also trying to fix the offset >issue - it is being correctly set from the on_playback_stopped requests, but I think it is overwritten by >the PauseIntent.
>When you ask alexa to pause, flask-ask first receives an OnPlaybackStopped request (bc she pauses to >listen to your command). Then immediately receives the Pause Intent, which seems to mess with the >syncing of the current_stream.

They pushed the changes last night and Flask-Ask has been upgraded to 0.8.4 in pip.

**Pull request closed without merging**
