### PR TITLE
Refactor English strings so we can extend to other languages easier.

### PR DESCRIPTION
**Pull request by fergyfresh**
As Amazon expands into other countries we could open ourselves to more contributors by easily allowing this code to be used in your language of choice and additionally allowing it to be easy to add your choice language if it doesn't exist. This is currently not easy and this is the first push towards this goal.

### CODE REVIEW

**Comment by stevenleeg** [comment]
Let me know when this is ready for review and I can give it a look. Awesome work!

**Comment by fergyfresh** [comment]
#173 #174 #175 should all submit pull requests off of my master https://github.com/fergyfresh/geemusic/ and do the translations in the `WORDS` dictionaries in `selection.py` and `playback.py` for whatever languages they need. If they don't I'm going to call this done with the ability to be extended to any language at any time, because of my work pulling out all the English strings into a data structure that supports switching the phrase based on the `LANGUAGE` environment variable.

**Comment by fergyfresh** [comment]
Alright @stevenleeg, we are all good on pulling out the English strings for the `selection.py` and `playback.py` stuff. Try it out, I tested a bunch of them last night.

**Comment by simonszu** [comment]
This is cool, but: There are several strings repeating itself, e.g. `loop_on` and `loop_off`. This is intended by design, since you associated the strings with the intent where they should be sent to Alexa. Just for curiosity: Have you considered associating strings not with their intents, but just with their content? So that you'll have a `no_songs_in_queue` string which is then used in both the `loop_on` and `loop_off` intent? 

The pros of this scheme is less work for the translator, because he doesn't need to define the same string on several places, the cons of this scheme is a slightly less flexible layout, since it results in every intent with this answer string having the same response.

**Comment by fergyfresh** [comment]
I did it for flexibility and clarities sake. It allows those strings to differ in the future and not cause too much confusion. You could certainly define strings that are reused before `WORDS`. But i honestly think that's more work than it's worth

**Comment by digiltd** [comment]
You have been busy :) 

Did you look at using Jinga templates? they are supported in flask-ask

https://github.com/johnwheeler/flask-ask/#jinja-templates
https://github.com/johnwheeler/flask-ask/tree/master/samples/spacegeek

**Comment by fergyfresh** [comment]
Damn you Sam! Always coming up with slightly better solutions than what I propse. It's like you have more experience than me or something :disappointed:, I haven't wrapped my head fully around how to do this yet. This is my first attempt at a multi-lingual app so, baby steps. I say we incorp this PR and then use jinja-templates and YAML after this is incorporated. Gives people a springboard to incorporate their languages as this was quick  and dirty.

**Comment by yamitzky** [comment]
I saw your PR and I am working on adding Japanese responses. 

I noticed several things on your work after I translated.

First, debug log messages does not have to be translated. e.g. `started`, `stopped`. `debug`. 

Second, "album A by B" is translated to "B no(の) album(アルバム) A", so `A -> B` is reversed to `B -> A`. I have no idea to fix. 🤔

**Comment by yamitzky** [comment]
Oops, I saw @digiltd 's proposal after I commented above.

Jinja template strategy solves the Japanese problem. `{{ song }} by {{ artist }}` can be translated to `{{ artist }} の {{ song }}`

**Comment by yamitzky** [comment]
In addition to that, I think `ja` is better than `jp` to indicate Japanese language. [c.f. ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

**Comment by fergyfresh** [comment]
Alright so @yamitzky and @digiltd. I could see how it would be really easy to implement my dictionary into YAML/jinja2 templates. But, do you guys have any idea on how we could swap on the `LANGUAGE=en` environment variable for using different YAML files by language?

**Comment by fergyfresh** [comment]
I'm very sorry if my `jp` vs. `ja` offended you. I googled the same thing I googled for finding the German one `de`, so I thought I was accurate. Thank you for the correction!

**Comment by fergyfresh** [comment]
@yamitzky we can also do this. instead of `"Playing album %s by %s" % ("The Album", "The Artist")` we can use `format` instead of the old-style `%` concat method. `"Playing album {0} by {1}".format("The Album", "The Artist")` allows you to swap the 0 and the 1 around which allows you to swap orders of the variables you concat into the string. It will allow us to finish this PR and let you implement your Japanese translations sooner rather than later.

**Comment by digiltd** [comment]
@fergyfresh yeah, sorry.. I didn't to mention the template thing after all your hard work. As you say, better to complete one thing before starting another :)

Have a look at https://github.com/m0ngr31/kodi-alexa it uses separate template files for the two supported languages (en & de). Though you could just require the user to rename their language YAML file (e.g. template.de.yaml) to the file that gets pulled in (e.g. template.yaml)

**Comment by fergyfresh** [comment]
Work for the sense of work isn't good. I'm just sad you don't creep my contributions more and you coulda saved me this original travesty.

**Comment by fergyfresh** [comment]
So we can kill this or incorp it. It works and I don't wanna look at it anymore. I'm going to eventually YAMLize it, but until then we should just push this in there I think.

**Comment by yamitzky** [comment]
>  we can use `format` instead of the old-style % concat method

Okay, sounds good!

**Comment by fergyfresh** [comment]
@yamitzsky I'm going to close this PR in favor of #179 if you want to hold off on your translations until I setup the new string structure that you'll have to translate to support you might save yourself some rework.

Thanks everyone for the suggestions and ideas on this PR, namely @digiltd and @yamitzky.

**Comment by fergyfresh** [comment]
I think so? Try setting an environment variable to `LANGUAGE=de`

**Pull request closed without merging**
