### PR TITLE
Added support to use exclusively your uploaded google music library. …

### PR DESCRIPTION
**Pull request by andrewdavisdev**
…This is for free users of Google Music who do not subscribe to unlimited google music.

Playing Songs, Artists and Albums from the Library are supported.

music.py:
- Added new Enviornment Variable: USE_LIBRARY_FIRST=true, this needs to be set for this to work
- Refactored get_thumbnail to take in the dictionary and have it handle the key check. Sometimes it did not have the key in the dictionary and would error. This way a default image can be set.
- Added _search_library_for_first to grab the first match in the Library
- Added _search_library to return a list of all matching based on query and query type from the Library

selection.py
- When playing an artist from the Library it will randomize the queue from that artist so every time you play an artist it is different, also Alexa will say "playing random library tracks" instead of "playing top tracks" when using the library from an artist
- When playing an album from the Library it will be in track sorted order

### CODE REVIEW

**Comment by andrewdavisdev** [comment]
Updated the PR with another commit to fix Playlists. See commit comments for details.

**Comment by digiltd** [comment]
I have tried this, whilst now I can get it to "start playing tracks from my library" (something I previously have not been able to do (on a free account))

When I say anything like "play music by madonna" it still looks for the storeid and I get the error`raise NotSubscribed("Store tracks require a subscription to stream.")`

**Comment by andrewdavisdev** [comment]
@digiltd Did you enable this Environment variable `{USE_LIBRARY_FIRST=true` ?
I just tried your query and it works for me. Normally I would do "play artist {artist name}" but "play music by {artist name}" is also working for me.

**Comment by digiltd** [comment]
@andrewdavisdev yup, well in the sense that I have added it to the .env file.

**Comment by loctruong96** [comment]
Wow this version work flawlessly for Free Google Music support. Well done. I deploy this on heroku, and set the environment variable to `USE_LIBRARY_FIRST=true` on the dyno and it just works (along with other standard variables in place, of course). Man, this made my night, thank you! 

P.S sometime alexa said she playing but nothing came out i think because google server is weird, especially on track that are 1 hour long but most of the request came back perfectly.

**Comment by jmahlman** [comment]
Your edits work great for me.  I do have some functions that cause an internal server error (500).
"List the latest albums by "
"List all albums by "

And some just return "I cannot find that" with errors in the heroku instance
"Play the latest album by "
"Play a different album"
"Play an album by "

The log from heroku:

> 017-09-01T13:25:07.382782+00:00 app[web.1]: {
2017-09-01T13:25:07.382796+00:00 app[web.1]:   "context": {
2017-09-01T13:25:07.382797+00:00 app[web.1]:     "AudioPlayer": {
2017-09-01T13:25:07.382798+00:00 app[web.1]:       "playerActivity": "IDLE"
2017-09-01T13:25:07.382799+00:00 app[web.1]:     },
2017-09-01T13:25:07.382799+00:00 app[web.1]:     "System": {
2017-09-01T13:25:07.382800+00:00 app[web.1]:       "application": {
2017-09-01T13:25:07.382801+00:00 app[web.1]:         "applicationId": "amzn1.ask.skill.209be610-73d7-4d46-b2d9-020dfd1d5acf"
2017-09-01T13:25:07.382801+00:00 app[web.1]:       },
2017-09-01T13:25:07.382801+00:00 app[web.1]:       "device": {
2017-09-01T13:25:07.382802+00:00 app[web.1]:         "supportedInterfaces": {}
2017-09-01T13:25:07.382802+00:00 app[web.1]:       },
2017-09-01T13:25:07.382803+00:00 app[web.1]:       "user": {
2017-09-01T13:25:07.382804+00:00 app[web.1]:         "userId": "amzn1.ask.account.AFQONEFAMWKFAPCKUC3OJ2WE2JPMSHAFY3DMFBBHUEJP3HJGN53WK6CD5GIOLBGVHDSJQMBH7IBC7XEJRMCVCRUGN4KER33VA3Z6LB7V67632EYKBQOMFXHVTQRQ26XKBKEQ6CXFXVTEKCZJLKLOKACYMHOYIMATS6DLXF756R6XQ3XTZVYKPCBXFT3C5KHNE67CYT5I7RFYNRI"
2017-09-01T13:25:07.382804+00:00 app[web.1]:       }
2017-09-01T13:25:07.382805+00:00 app[web.1]:     }
2017-09-01T13:25:07.382805+00:00 app[web.1]:   },
2017-09-01T13:25:07.382805+00:00 app[web.1]:   "request": {
2017-09-01T13:25:07.382806+00:00 app[web.1]:     "intent": {
2017-09-01T13:25:07.382806+00:00 app[web.1]:       "name": "GeeMusicPlayAlbumByArtistIntent",
2017-09-01T13:25:07.382807+00:00 app[web.1]:       "slots": {
2017-09-01T13:25:07.382807+00:00 app[web.1]:         "artist_name": {
2017-09-01T13:25:07.382807+00:00 app[web.1]:           "name": "artist_name",
2017-09-01T13:25:07.382808+00:00 app[web.1]:           "value": "pink Floyd"
2017-09-01T13:25:07.382808+00:00 app[web.1]:         }
2017-09-01T13:25:07.382808+00:00 app[web.1]:       }
2017-09-01T13:25:07.382809+00:00 app[web.1]:     },
2017-09-01T13:25:07.382809+00:00 app[web.1]:     "locale": "en-US",
2017-09-01T13:25:07.382809+00:00 app[web.1]:     "requestId": "EdwRequestId.2a5f18d5-b588-4acb-b948-ec7a4f6c834e",
2017-09-01T13:25:07.382810+00:00 app[web.1]:     "timestamp": "2017-09-01T13:25:07Z",
2017-09-01T13:25:07.382810+00:00 app[web.1]:     "type": "IntentRequest"
2017-09-01T13:25:07.382811+00:00 app[web.1]:   },
2017-09-01T13:25:07.382811+00:00 app[web.1]:   "session": {
2017-09-01T13:25:07.382811+00:00 app[web.1]:     "application": {
2017-09-01T13:25:07.382812+00:00 app[web.1]:       "applicationId": "amzn1.ask.skill.209be610-73d7-4d46-b2d9-020dfd1d5acf"
2017-09-01T13:25:07.382812+00:00 app[web.1]:     },
2017-09-01T13:25:07.382812+00:00 app[web.1]:     "attributes": {},
2017-09-01T13:25:07.382813+00:00 app[web.1]:     "new": false,
2017-09-01T13:25:07.382813+00:00 app[web.1]:     "sessionId": "SessionId.3026831e-09f7-432b-b5bc-28ea27d35c86",
2017-09-01T13:25:07.382813+00:00 app[web.1]:     "user": {
2017-09-01T13:25:07.382814+00:00 app[web.1]:       "accessToken": null,
2017-09-01T13:25:07.382814+00:00 app[web.1]:       "userId": "amzn1.ask.account.AFQONEFAMWKFAPCKUC3OJ2WE2JPMSHAFY3DMFBBHUEJP3HJGN53WK6CD5GIOLBGVHDSJQMBH7IBC7XEJRMCVCRUGN4KER33VA3Z6LB7V67632EYKBQOMFXHVTQRQ26XKBKEQ6CXFXVTEKCZJLKLOKACYMHOYIMATS6DLXF756R6XQ3XTZVYKPCBXFT3C5KHNE67CYT5I7RFYNRI"
2017-09-01T13:25:07.382814+00:00 app[web.1]:     }
2017-09-01T13:25:07.382815+00:00 app[web.1]:   },
2017-09-01T13:25:07.382817+00:00 app[web.1]:   "version": "1.0"
2017-09-01T13:25:07.382820+00:00 app[web.1]: }
2017-09-01T13:25:07.383235+00:00 app[web.1]: {
2017-09-01T13:25:07.383236+00:00 app[web.1]:   "offsetInMilliseconds": 0,
2017-09-01T13:25:07.383237+00:00 app[web.1]:   "playerActivity": "IDLE",
2017-09-01T13:25:07.383238+00:00 app[web.1]:   "token": "6ea36ce5-5b7f-4400-8ee8-8f3c6dd61bc8",
2017-09-01T13:25:07.383239+00:00 app[web.1]:   "url": "https://arcane-savannah-47650.herokuapp.com/alexa/stream/6e82075e-87c2-3dc8-8737-cc48a72be6ab"
2017-09-01T13:25:07.383239+00:00 app[web.1]: }
2017-09-01T13:25:08.005878+00:00 app[web.1]: Exception in thread Thread-11:
2017-09-01T13:25:08.005896+00:00 app[web.1]: Traceback (most recent call last):
2017-09-01T13:25:08.005897+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
2017-09-01T13:25:08.005919+00:00 app[web.1]:     self.run()
2017-09-01T13:25:08.005920+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/threading.py", line 864, in run
2017-09-01T13:25:08.005921+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2017-09-01T13:25:08.005922+00:00 app[web.1]:   File "/app/geemusic/utils/music.py", line 70, in index_library
2017-09-01T13:25:08.005922+00:00 app[web.1]:     self.logger.debug('Fetching library...')
2017-09-01T13:25:08.005923+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'debug'
2017-09-01T13:25:08.005928+00:00 app[web.1]: 
2017-09-01T13:25:08.727580+00:00 heroku[router]: at=info method=POST path="/alexa" host=arcane-savannah-47650.herokuapp.com request_id=abe1e68d-8d92-4d80-8616-1ca83a7b224a fwd="72.21.217.174" dyno=web.1 connect=0ms service=1361ms status=200 bytes=323 protocol=https
2017-09-01T13:25:08.722472+00:00 app[web.1]: {
2017-09-01T13:25:08.722486+00:00 app[web.1]:   "response": {
2017-09-01T13:25:08.722487+00:00 app[web.1]:     "outputSpeech": {
2017-09-01T13:25:08.722489+00:00 app[web.1]:       "text": "Sorry, I couldn't find any albums.",
2017-09-01T13:25:08.722490+00:00 app[web.1]:       "type": "PlainText"
2017-09-01T13:25:08.722490+00:00 app[web.1]:     },
2017-09-01T13:25:08.722491+00:00 app[web.1]:     "shouldEndSession": true
2017-09-01T13:25:08.722492+00:00 app[web.1]:   },
2017-09-01T13:25:08.722492+00:00 app[web.1]:   "sessionAttributes": {},
2017-09-01T13:25:08.722493+00:00 app[web.1]:   "version": "1.0"
2017-09-01T13:25:08.722497+00:00 app[web.1]: }
2017-09-01T13:25:08.722805+00:00 app[web.1]: 10.33.230.36 - - [01/Sep/2017 13:25:08] "POST /alexa HTTP/1.1" 200 -

Not sure if this is a problem with your commit or the master.

**Comment by stevenleeg** [comment]
Looks like there are still some issues on this PR and it hasn't seen any love in a while. I'm going to close this for the time being but am still open to merging it if there are updates, so feel free to re-open in the future!

**Pull request closed without merging**
