### PR TITLE
Loop Support

### PR DESCRIPTION
**Pull request by PostsDesert**
- Loop support with [playlist resets](https://github.com/stevenleeg/geemusic/issues/21)
- Modified shuffle intent so it will not break when a user tries to shuffle and then loop tracks.
- Makes `AMAZON.StartOver` start over the song instead of queueing it.
- Slightly lowers the matching criteria for playlist selection (80 was unable to match many of my playlist) 
- This also fixed a bug with the Shuffle support that makes it not enqueue the correct song when it's disabled
- Added a few more SampleUtterances

### CODE REVIEW

**Comment by stevenleeg** [comment]
Hey, this looks great but I'm still a bit confused by the implementation, as it seems like this will cause the queue to loop regardless of whether or not the user has started loop mode. Am I reading this wrong or is that the intended behavior (it sounded like that was the case based on what you were saying in #21, but I just want to be sure).

**Comment by PostsDesert** [comment]
Yes, that is the intended behavior but that kinda defeats the purpose of the loop function. It was designed to loop playlists so you could set music on you Alexa and it would continue playing similar to GPM. I've set it to require a minimum of 5 track to loop the queue so that should cover single track plus a few queued ones.

**Comment by stevenleeg** [comment]
hmm I don't really agree with looping being a default behavior. it seems to me like the only context where a queue should loop would be when loop mode is set to on (otherwise the playlist/queue would just end once it reached the last song).

**Comment by PostsDesert** [comment]
I can remove it if you want but it will break the current implementation of how I have loop set up to work. Loop mode when set to on just loops the one track that is currently playing.

**Comment by PostsDesert** [comment]
Slightly modified and moved to #41.

**Pull request closed without merging**
