### PR TITLE
Adapted the new JSON format created in #200 to work with non-US slot types

### PR DESCRIPTION
**Pull request by laurilarjo**
The new Alexa's interactionModel JSON was created here https://github.com/stevenleeg/geemusic/pull/200, so I took that and adapted it to work with non-US slot types.
I basically used the already existing MUSICALBUM.txt, MUSICGROUP.txt etc for the example types, and converted them into the JSON format which Amazon now requests.

### CODE REVIEW

**Comment by pquerner** [comment]
What about the README.md ?

**Comment by laurilarjo** [comment]
Updated readme also. But stuff might conflict once #200 is merged.

**Comment by stevenleeg** [comment]
Looks like there are some conflicts. If someone could get those patched up I'm happy to merge this!

**Comment by laurilarjo** [comment]
Pulled in latest master and solved merge conflicts. Voilà.

**Comment by stevenleeg** [comment]
Sorry for the delay on this one. Merged, and thanks for your contribution!

**Pull request merged**
