### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by BigLouis87**
Implementation of #266

### CODE REVIEW

**Comment by BigLouis87** [comment]
I don't know why it fails to build the utterances... anyone more expert than me wants to try? Thanks

**Comment by fergyfresh** [comment]
What do you mean? Fails to build the utterances? Did you remember to `export LANGUAGE=it`

**Comment by fergyfresh** [comment]
Any work on this yet?

**Comment by fergyfresh** [comment]
Closing due to lack of interest.

**Pull request closed without merging**
